server {
    listen 80;
    
    # Directorio donde Nginx encontrará los archivos de React
    root /usr/share/nginx/html;
    index index.html;

    # MAGIA PARA REACT ROUTER: Redirige todo al index.html
    location / {
        try_files $uri $uri/ /index.html;
    }

    # Optimización: Caché para imágenes, css y js
    location ~* \.(?:ico|css|js|gif|jpe?g|png|woff2?|eot|ttf|svg)$ {
        expires 6M;
        access_log off;
        add_header Cache-Control "public";
    }
}