FROM node:20-alpine

WORKDIR /app

# Copiamos dependencias e instalamos
COPY package*.json ./
RUN npm install

# Copiamos el código fuente
COPY . .

# Usamos tsx para arrancar directamente tu archivo original. ¡Cero errores de rutas!
CMD ["npx", "tsx", "src/index.ts"]