FROM node:20-alpine
WORKDIR /app
COPY package*.json ./
# Instalamos solo dependencias reales (omite las de desarrollo)
RUN npm install --production
COPY . .
EXPOSE 3000

# IMPORTANTE: Asegúrate de tener el script "start" en tu package.json (ej. "start": "node index.js")
CMD ["npm", "start"]